server.port=8080

springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.defaultModelsExpandDepth=-1

app.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
app.datasource.username=${MYSQLUSER}
app.datasource.password=${MYSQLPASSWORD}
app.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
app.datasource.configuration.maximum-pool-size=30


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB
spring.servlet.multipart.location=${java.io.tmpdir}